### ISSUE TITLE
Brushing dirt causes it to break before finishing 

### ISSUE THREAD

**Issue by YnwLNE** [capsey/archeology-mod#22]
When in survival and using the brush it breaks the block midway through, making it impossible to do the feature

I'm on latest version of everything.
modlist: https://pastebin.com/FEq6hqkL

![2022-03-23_19 29 23](https://user-images.githubusercontent.com/81484850/159830237-f86ac2e6-6523-4f1f-a897-963fac8db4fd.png)

**Comment by capsey** [comment]
This is intended feature, while brushing block breaks if you don't move your camera enough. It is described in the mod description under Brushing Excavation Blocks section:

* While brushing, you should move your camera to stop the block from breaking. If you don't move enough, the block will break eventually, and you won't get anything. The more oxidized your brush is, the faster the block breaks, and therefore faster you need to move.
    * Actually, Mojang showed this feature as completely opposite: if you move your screen too much, the block will break. You can enable this instead, if you prefer it more than mine.

Block cracking is indication how close you're to failing. Or did you meant something different?

**Comment by capsey** [comment]
No problems, I think that's my bad that I didn't make this important feature clear enough
