### ISSUE TITLE
Other players crash when excavating blocks on LAN worlds/dedicated servers

### ISSUE THREAD

**Issue by Mnky313** [capsey/archeology-mod#52]
to reproduce have one player start a server (Open to LAN or dedicated server) & attempt to brush an excavation block with a second player nearby.
(The player who crashes (the one not excavating) needs to have the excavating player loaded in as well).

`Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_745 cannot be cast to class net.capsey.archeology.entity.BrushingPlayerEntity (net.minecraft.class_745 and net.capsey.archeology.entity.BrushingPlayerEntity are in unnamed module of loader`
[crash-2022-10-03_13.14.16-client.txt](https://github.com/capsey/archeology-mod/files/9699510/crash-2022-10-03_13.14.16-client.txt)

**Comment by capsey** [comment]
I released new version with the fix (v0.2.4), hope now it doesn't crash! Close the issue if it worked
