### ISSUE TITLE
Request permission to carry archeology-mod to MCBBS

### ISSUE THREAD

**Issue by LYOfficial** [capsey/archeology-mod#56]
Hi, I am a Chinese user, I have used archeology-mod for a long time, I always download every update to see if there is anything new. It does a great job, and it's very much like what Mojang describes in Minecraft Live. 
But China doesn't have normal fast access to curseforge and GitHub.Can I apply for permission to carry archeology-mod to MCBBS (a Chinese Minecraft forum) so that more Chinese players can use it?Thank you very much!

**Comment by capsey** [comment]
Yes, go ahead
